// v0.1.2.5 BASELINE — Home Player Box, Weather, Today, Resources, and
// Navigation redesign, plus the Development -> Personal Growth move.
// v0.1.2.11 — Today restructured per home-definitive-spec.md, Resources
// header centered, v0.02.1.3 crest icon pack wired in.
const CACHE='rpg-v0.1.3-daadb8bc';
const ASSETS=[
  './',
  './index.html',
  './styles.css?v=0.1.2.19',
  './v0.02.4.3-player-box.css?v=0.1.2.5',
  './v0.02.4.4-player-box-cleanup.css?v=0.1.2.5',
  './v0.02.4.5-player-box-layout.css?v=0.1.2.5',
  './v0.02.4.6-player-frame-controls.css?v=0.1.2.5',
  './v0.02.4.11-player-box-progression-fix.css?v=0.1.2.6',
  './v0.02.4.12-player-box-shared-frame.css?v=0.1.2.6',
  './v0.02.4.13-today-controls-extension.css?v=0.1.2.7',
  './v0.02.4.14-home-frames-removed.css?v=0.1.2.7',
  './v0.02.4.7-weather-panel.css?v=0.1.2.6',
  './v0.02.4.8-today-panel.css?v=0.1.2.8',
  './v0.02.4.9-resources-panel.css?v=0.1.2.11',
  './v0.02.4.10-navigation.css?v=0.1.3.4',
  './v0.02.4.15-today-panels.css?v=0.1.2.16',
  './v0.02.4.17-flat-panel-background.css?v=0.1.2.12',
  './v0.02.4.18-player-panel-cleanup.css?v=0.1.2.18',
  './v0.02.4.19-weather-forecast-cleanup.css?v=0.1.2.12',
  './v0.02.4.20-secondary-panels-cleanup.css?v=0.1.2.17',
  './v0.02.4.21-resources-bar-redesign.css?v=0.1.2.18',
  './v0.02.5-home-baseline.css?v=0.1.2.20',
  './v0.02.6-home-final-polish.css?v=0.1.2.22',
  './v0.02.7-adventure-campaign.css?v=0.1.2.29',
  './v0.02.8-achievements-page.css?v=0.1.2.28',
  './v0.02.9-quests-hub.css?v=0.1.2.35',
  './v0.02.10-training-journal.css?v=0.1.2.56',
  './styles/training-v3/00-training-tokens.css?v=0.1.0.4',
  './styles/training-v3/categories/running.css?v=0.1.0.1',
  './styles/training-v3/categories/strength.css?v=0.1.0.1',
  './styles/training-v3/categories/cycling.css?v=0.1.0.1',
  './styles/training-v3/categories/climbing.css?v=0.1.0.1',
  './styles/training-v3/categories/sports.css?v=0.1.0.1',
  './styles/training-v3/categories/rowing.css?v=0.1.0.1',
  './styles/training-v3/categories/skiing.css?v=0.1.0.1',
  './styles/training-v3/categories/health-training.css?v=0.1.0.1',
  './styles/training-v3/categories/yoga.css?v=0.1.0.2',
  './styles/training-v3/categories/swimming.css?v=0.1.0.1',
  './styles/training-v3/categories/walking-hiking.css?v=0.1.0.1',
  './styles/training-v3/categories/calisthenics.css?v=0.1.0.1',
  './styles/training-v3/01-training-shell.css?v=0.1.0.1',
  './styles/training-v3/02-training-cards.css?v=0.1.0.3',
  './styles/training-v3/04-training-gateways.css?v=0.1.0.4',
  './styles/training-v3/05-training-tabs.css?v=0.1.0.1',
  './styles/training-v3/06-training-metrics.css?v=0.1.0.1',
  './styles/training-v3/07-training-rows.css?v=0.1.0.2',
  './styles/training-v3/08-training-actions.css?v=0.1.0.1',
  './styles/training-v3/09-training-week-calendar.css?v=0.1.0.1',
  './styles/training-v3/10-training-glass-icons-buttons.css?v=0.1.0.3',
  './styles/training-v3/11-training-specialist-hero.css?v=0.1.0.2',
  './styles/training-v3/12-training-legacy-retirement.css?v=0.1.0.4',
  './styles/training-v3/13-training-modals.css?v=0.1.0.2',
  './styles/training-v3/14-library-scroll-rows.css?v=0.1.0.5',
  './styles/integrations.css?v=0.1.0.1',
  './styles/achievement-card/00-ach-tokens.css?v=0.1.0.1',
  './styles/achievement-card/01-ach-card.css?v=0.1.0.4',
  './styles/achievement-card/02-ach-surfaces.css?v=0.1.0.2',
  './styles/achievement-card/03-ach-motion.css?v=0.1.0.1',
  './v0.02.11-journeys.css?v=0.1.2.33',
  './v0.02.45-illustrated-journey-map.css?v=0.1.0.2',
  './v0.02.43-journey-catalogue.css?v=0.1.0.3',
  './v0.02.12-home-modules.css?v=0.1.2.32',
  './styles/home-v4/00-home-tokens.css?v=0.3.0.1',
  './v0.02.13-home-v2-visuals.css?v=0.1.2.38',
  './v0.02.14-home-widget-shell.css?v=0.1.2.36',
  './v0.02.15-home-widget-player-status.css?v=0.1.2.115',
  './v0.02.16-home-parchment-modules.css?v=0.1.2.91',
  './v0.02.18-home-feature-module.css?v=0.1.2.3',
  './v0.02.19-home-standard-module.css?v=0.1.2.10',
  './v0.02.20-home-parchment-material.css?v=0.1.2.6',
  './v0.02.21-home-parchment-tokens.css?v=0.1.2.7',
  './v0.02.22-home-component-primitives.css?v=0.1.2.6',
  './v0.02.24-home-classic-hud-character-stats.css?v=0.1.2.5',
  './v0.02.25-home-classic-hud-phase-3-6.css?v=0.1.2.14',
  './v0.02.26-home-player-hud-rebuild.css?v=0.1.2.11',
  './styles/quests-v4/00-quest-tokens.css?v=0.2.0.4',
  './styles/quests-v4/01-quest-glass.css?v=0.2.0.3',
  './styles/quests-v4/02-quest-layout.css?v=0.2.0.4',
  './styles/quests-v4/03-quest-header.css?v=0.2.0.3',
  './styles/quests-v4/04-quest-gateways.css?v=0.2.0.4',
  './styles/quests-v4/05-quest-icons.css?v=0.2.0.3',
  './styles/quests-v4/06-quest-buttons.css?v=0.2.0.3',
  './styles/quests-v4/07-quest-cards.css?v=0.2.0.3',
  './styles/quests-v4/08-quest-rows.css?v=0.2.0.4',
  './styles/quests-v4/09-quest-tabs.css?v=0.2.0.3',
  './styles/quests-v4/10-quest-progress.css?v=0.2.0.3',
  './styles/quests-v4/11-quest-forms.css?v=0.2.0.3',
  './styles/quests-v4/12-quest-modals.css?v=0.2.0.3',
  './styles/quests-v4/13-quest-popovers.css?v=0.2.0.3',
  './styles/quests-v4/14-quest-toasts.css?v=0.2.0.3',
  './styles/quests-v4/15-quest-responsive.css?v=0.2.0.3',
  './styles/quests-v4/16-quest-themes.css?v=0.2.0.3',
  './styles/quests-v4/17-quest-quick.css?v=0.2.0.1',
  './styles/home-quick-quest.css?v=0.1.0.1',
  './styles/personal-growth/00-pg-theme.css?v=0.1.0.3',
  './styles/personal-growth/01-pg-components.css?v=0.1.0.12',
  './styles/personal-growth/02-pg-pages.css?v=0.1.0.7',
  './styles/personal-growth/03-pg-detail.css?v=0.1.0.2',
  './styles/weekly-recap/00-recap.css?v=0.1.0.1',
  './styles/onboarding/00-onboarding.css?v=0.1.0.1',
  './styles/notifications/00-notifications.css?v=0.1.0.1',
  './styles/library/00-lib-theme.css?v=0.1.0.1',
  './styles/library/01-lib-components.css?v=0.1.0.2',
  './styles/library/02-lib-detail.css?v=0.1.0.2',
  './styles/inventory-v1/00-inv-tokens.css?v=0.1.0.1',
  './styles/inventory-v1/01-inv-components.css?v=0.1.0.3',
  './styles/economy/00-economy.css?v=0.1.0.7',
  './styles/home-compact/00-compact-trackers.css?v=0.1.0.4',
  './styles/self-care/00-self-care.css?v=0.1.0.5',
  './app.js?v=0.1.2.252',
  './v0.02.17-exercise-library.js?v=0.1.2.17',
  './v0.02.4-integration.js?v=0.1.2.86',
  './v0.02.49-sleep-hidden-progress.js?v=0.1.3.0',
  './v0.02.4.1-frame-hotfix.js?v=0.1.2.5',
  './v0.02.4.2-character.js?v=0.1.2.9',
  './v0.02.4.3-player-box.js?v=0.1.2.57',
  './v0.02.4.4-player-box-cleanup.js?v=0.1.2.5',
  './v0.02.4.5-player-box-layout.js?v=0.1.2.5',
  './v0.02.4.6-player-frame-controls.js?v=0.1.2.5',
  './v0.02.4.11-player-box-progression-fix.js?v=0.1.2.34',
  './v0.02.4.7-weather-panel.js?v=0.1.2.5',
  './v0.02.4.8-today-panel.js?v=0.1.2.9',
  './v0.02.4.9-resources-panel.js?v=0.1.2.6',
  './v0.02.4.10-navigation.js?v=0.1.2.6',
  './v0.02.4.13-today-controls-extension.js?v=0.1.2.34',
  './v0.02.4.16-resources-header-fix.js?v=0.1.2.13',
  './v0.02.15-home-widget-player-status.js?v=0.1.2.109',
  './v0.02.27-health-connect-bridge.js?v=0.1.2.5',
  './v0.02.29-training-gear.js?v=0.1.2.2',
  './v0.02.30-training-import.js?v=0.1.2.1',
  './v0.02.31-strava-adapter.js?v=0.1.2.1',
  './v0.02.32-integrations-ui.js?v=0.1.2.1',
  './v0.02.33-quick-quests.js?v=0.1.2.4',
  './v0.02.34-personal-growth.js?v=0.1.0.11',
  './v0.02.35-library.js?v=0.1.0.6',
  './v0.02.46-economy-config.js?v=0.1.0.2',
  './v0.02.36-inventory.js?v=0.1.1.1',
  './v0.02.37-inventory-ui.js?v=0.1.1.4',
  './v0.02.47-economy-core.js?v=0.1.1.1',
  './v0.02.48-economy-ui.js?v=0.1.1.1',
  './v0.02.50-self-care.js?v=0.1.1.3',
  './v0.02.51-self-care-ui.js?v=0.1.0.2',
  './v0.02.52-pg-habits-hobbies-detail.js?v=0.1.0.3',
  './v0.02.53-pg-reading-nook.js?v=0.1.0.2',
  './v0.02.54-pg-records-feed.js?v=0.1.0.2',
  './v0.02.55-weekly-recap.js?v=0.1.0.1',
  './v0.02.56-onboarding.js?v=0.1.0.2',
  './v0.02.57-notifications.js?v=0.1.0.2',
  './v0.02.58-dev-tools.js?v=0.1.0.2',
  './v0.02.59-compact-home-trackers.js?v=0.1.0.3',
  './v0.02.60-scroll-bars.js?v=0.1.0.4',
  './v0.02.39-world-tours-map.js?v=0.1.0.2',
  './v0.02.44-illustrated-journey-map.js?v=0.1.0.8',
  './v0.02.40-hadrians-wall-illustrated-map.js?v=0.1.0.5',
  './v0.02.61-rome-illustrated-map.js?v=0.1.0.1',
  './v0.02.42-journey-catalogue.js?v=0.1.0.5',
  './manifest.json',
  './version.json',
  './assets/Class System/Icons/Starter Classes/novice_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/warrior_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scout_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scholar_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/artisan_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/steward_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/diplomat_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/adventurer_icon.png?v=0.1.2.5',
  './assets/Character/Stats/stat_str.png?v=0.1.2.5',
  './assets/Character/Stats/stat_dex.png?v=0.1.2.5',
  './assets/Character/Stats/stat_con.png?v=0.1.2.5',
  './assets/Character/Stats/stat_int.png?v=0.1.2.5',
  './assets/Character/Stats/stat_wis.png?v=0.1.2.5',
  './assets/Character/Stats/stat_cha.png?v=0.1.2.5',
  './assets/Training/Variant Other 2.png?v=0.1.2.5',
  './assets/Home/V3/Material/PARCHMENT_TEXTURE_512.png',
  './assets/Home/V3/Character/Stats/STAT_HP.png',
  './assets/Home/V3/Character/Stats/STAT_STAMINA.png',
  './assets/Home/V3/Character/Stats/STAT_DAMAGE.png',
  './assets/Home/V3/Character/Stats/STAT_DEFENCE.png',
  './assets/Home/V3/Character/Stats/STAT_FOCUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_STATUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_PORTRAIT.png',
  './assets/Home/Widget Family/BADGE_HOME_PLAYER_LEVEL.png',
  './assets/Home/Widget Family/BANNER_HOME_WIDGET_FEATURE.png',
  './assets/Home/Widget Family/PANEL_HOME_FEATURE_MEDIUM.png',
  './assets/Home/Widget Family/PANEL_HOME_STANDARD.png',
  './assets/Home/Widget Family/PANEL_HOME_COMPACT.png',
  './assets/Home/Widget Family/HEADER_HOME_WIDGET.png',
  './assets/Home/Widget Family/BUTTON_HOME_WIDGET.png',
  './assets/Home/Widget Family/INSET_HOME_STAT.png',
  './assets/Home/Widget Family/DIVIDER_HOME_WIDGET.png',
  './assets/backgrounds/home/BG_HOME_DAY.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_SUNSET.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_NIGHT.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_RAIN.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_TOP.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_BOTTOM.png?v=0.1.2.33',
  './assets/UI/shared/overlays/VIGNETTE_HOME.png?v=0.1.2.33',
  './assets/UI/shared/overlays/FX_HOME_RAIN.png?v=0.1.2.33',
  './assets/Home/Variant 8/Variant 8 - Player Panel Frame Only.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings Control Fix.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Player Panel Overlay.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Class Icon Frame.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Level Badge.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Help.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - HP.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Stamina.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Damage.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Defence.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Focus.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Streak.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Today.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Next Reward.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - XP Bar.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Divider.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Common_First_Sip.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Uncommon_Well_Watered.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Rare_Hydration_Habit.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Epic_River_Runner.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Legendary_The_Human_Reservoir.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Mythic_Ocean_in_Mortal_Form.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Secret_Is_This_Mostly_Water_Now.webp?v=0.1.2.5',
  './assets/Achievements/achievement_placeholder_not_ready_yet.webp?v=0.1.2.21',
  './assets/Daily_Challenge.png',
  './assets/Development.png',
  './assets/Resources.png',
  './assets/Home_Logo.png',
  './assets/history_icon.png',
  './assets/habits_tracker_icon.png',
  './assets/bonus_icon.png',
  './assets/archive_icon.png',
  './assets/resources/home_resources_tracker_badge_variant_b_v1.png',
  './assets/resources/home_resources_history_badge_variant_b_v1.png',
  './assets/app-icon-192.png',
  './assets/app-icon-512.png',
  './assets/app-icon-maskable-192.png',
  './assets/app-icon-maskable-512.png',
  './assets/apple-touch-icon.png',
  './assets/UI/nav_menu_button.png?v=0.1.2.5',
  './assets/UI/nav_radial_background.png?v=0.1.2.5',
  './assets/UI/nav_storage.png?v=0.1.2.5',
  './assets/UI/nav_personal_growth.png?v=0.1.2.5',
  './assets/UI/nav_quest_board.png?v=0.1.2.5',
  './assets/UI/nav_training.png?v=0.1.2.5',
  './assets/UI/nav_achievements.png?v=0.1.2.5',
  './assets/UI/nav_loot.png?v=0.1.2.5',
  './assets/UI/nav_library.png?v=0.1.2.5',
  './assets/UI/nav_social.png?v=0.1.2.5',
  './assets/nav_quest_board.png',
  './assets/social.png',
  './assets/Character/ailment_cold.png',
  './assets/Character/ailment_custom.png',
  './assets/Character/ailment_dehydrated.png',
  './assets/Character/ailment_fatigued.png',
  './assets/Character/ailment_fever.png',
  './assets/Character/ailment_headache.png',
  './assets/Character/ailment_injury.png',
  './assets/Character/ailment_knee_pain.png',
  './assets/Character/ailment_sleep_deprived.png',
  './assets/Character/ailment_sore_legs.png',
  './assets/Character/ailment_stomach_bug.png',
  './assets/Character/menu_equipment.png',
  './assets/Character/menu_profile_setup.png',
  './assets/Character/menu_rewards.png',
  './assets/Character/menu_skills.png',
  './assets/Training/archery.png?v=0.1.2.5',
  './assets/Training/basketball.png?v=0.1.2.5',
  './assets/Training/boxing.png?v=0.1.2.5',
  './assets/Training/climbing.png?v=0.1.2.5',
  './assets/Training/connection_apple_health.png?v=0.1.2.5',
  './assets/Training/connection_coros.png?v=0.1.2.5',
  './assets/Training/connection_fit_import.png?v=0.1.2.5',
  './assets/Training/connection_garmin.png?v=0.1.2.5',
  './assets/Training/connection_google_fit.png?v=0.1.2.5',
  './assets/Training/connection_health_connect.png?v=0.1.2.5',
  './assets/Training/connection_polar.png?v=0.1.2.5',
  './assets/Training/connection_strava.png?v=0.1.2.5',
  './assets/Training/connection_trainingpeaks.png?v=0.1.2.5',
  './assets/Training/connection_zwift.png?v=0.1.2.5',
  './assets/Training/cycling.png?v=0.1.2.5',
  './assets/Training/dance.png?v=0.1.2.5',
  './assets/Training/equestrian.png?v=0.1.2.5',
  './assets/Training/football.png?v=0.1.2.5',
  './assets/Training/golf.png?v=0.1.2.5',
  './assets/Training/hiking.png?v=0.1.2.5',
  './assets/Training/interval_run.png?v=0.1.2.5',
  './assets/Training/kayaking.png?v=0.1.2.5',
  './assets/Training/long_run.png?v=0.1.2.5',
  './assets/Training/martial_arts.png?v=0.1.2.5',
  './assets/Training/mobility.png?v=0.1.2.5',
  './assets/Training/recovery.png?v=0.1.2.5',
  './assets/Training/rest.png?v=0.1.2.5',
  './assets/Training/rowing.png?v=0.1.2.5',
  './assets/Training/rugby.png?v=0.1.2.5',
  './assets/Training/running.png?v=0.1.2.5',
  './assets/Training/skiing.png?v=0.1.2.5',
  './assets/Training/strength.png?v=0.1.2.5',
  './assets/Training/swimming.png?v=0.1.2.5',
  './assets/Training/table_tennis.png?v=0.1.2.5',
  './assets/Training/tennis.png?v=0.1.2.5',
  './assets/Training/trail_hiking.png?v=0.1.2.5',
  './assets/Training/volleyball.png?v=0.1.2.5',
  './assets/Training/yoga.png?v=0.1.2.5',
  './assets/weather-clear-night.png',
  './assets/weather-sleet.png',
  './assets/shared/home_shared_panel_frame_foreground_v8.png?v=0.1.2.5',
  './assets/today/home_today_main_quest_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_physical_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_mental_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_social_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_random_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_identity_icon_v1.png?v=0.1.2.18',
  './assets/today/home_today_daily_puzzle_icon_v1.png?v=0.1.2.18',
  './assets/Adventure/lost_fortress_campaign_banner_v1.png?v=0.1.2.19',
  './assets/icons/navigation/NAV_QUEST_BOARD.png?v=0.01.8.7.5',
  './assets/icons/navigation/NAV_TRAINING.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_CHARACTER.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LIBRARY.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_QUESTS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_ADVENTURES.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LOG.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_GROWTH.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_SOCIAL.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_REWARDS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_HOME.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_INVENTORY.png?v=0.01.8.7.6',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_262.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_262_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_288.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_288_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_324.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_324_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_304.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_304_2x.png?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_352.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_352_2x.png?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_412.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_412_2x.png?v=0.1.3.1',
  './assets/Home/V3/Identity/HUD_REWARDS_40.png',
  './assets/Home/V3/Identity/HUD_REWARDS_80.png',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_BACKING_50.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_SPOKES.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_STYLIZED.png?v=0.1.2.1',
  './assets/icons/development/ICON_DEV_WORD.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_WISDOM.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_CHALLENGE.png?v=0.1.2.27',
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('rpg-')&&k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  event.respondWith(fetch(event.request).then(response=>{
    const copy=response.clone();
    caches.open(CACHE).then(cache=>cache.put(event.request,copy)).catch(()=>{});
    return response;
  }).catch(()=>caches.match(event.request).then(hit=>{
    if(hit)return hit;
    if(event.request.mode==='navigate')return caches.match('./index.html');
    return Response.error();
  })));
});

/* RPG-0071: tapping a reminder (a system notification shown by the notification engine) focuses the app, or opens it. */
self.addEventListener('notificationclick', event => {
  event.notification.close();
  event.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) { if ('focus' in c) return c.focus(); }
    return self.clients.openWindow('./');
  }));
});
