// v0.1.2.5 BASELINE — Home Player Box, Weather, Today, Resources, and
// Navigation redesign, plus the Development -> Personal Growth move.
// v0.1.2.11 — Today restructured per home-definitive-spec.md, Resources
// header centered, v0.02.1.3 crest icon pack wired in.
const CACHE='rpg-v0.1.3-cb4979e4';
const ASSETS=[
  './',
  './index.html',
  './styles.css?v=b7980329',
  './v0.02.4.3-player-box.css?v=32a9f32b',
  './v0.02.4.4-player-box-cleanup.css?v=8d5f2f68',
  './v0.02.4.5-player-box-layout.css?v=03b0137d',
  './v0.02.4.6-player-frame-controls.css?v=2adbc0dd',
  './v0.02.4.11-player-box-progression-fix.css?v=b8348672',
  './v0.02.4.12-player-box-shared-frame.css?v=091d643c',
  './v0.02.4.13-today-controls-extension.css?v=350ee48d',
  './v0.02.4.14-home-frames-removed.css?v=7d624ac3',
  './v0.02.4.7-weather-panel.css?v=c006d5cc',
  './v0.02.4.8-today-panel.css?v=1f17c7b7',
  './v0.02.4.9-resources-panel.css?v=ece0c6d3',
  './v0.02.4.10-navigation.css?v=fc22aaab',
  './v0.02.4.15-today-panels.css?v=5d69eecf',
  './v0.02.4.17-flat-panel-background.css?v=2bbbe457',
  './v0.02.4.18-player-panel-cleanup.css?v=392b1e4f',
  './v0.02.4.19-weather-forecast-cleanup.css?v=0f327247',
  './v0.02.4.20-secondary-panels-cleanup.css?v=79ead383',
  './v0.02.4.21-resources-bar-redesign.css?v=775ba6c0',
  './v0.02.5-home-baseline.css?v=21b7edea',
  './v0.02.6-home-final-polish.css?v=62bdcecf',
  './v0.02.7-adventure-campaign.css?v=5de5355a',
  './v0.02.8-achievements-page.css?v=2422b727',
  './v0.02.9-quests-hub.css?v=26c4b412',
  './v0.02.10-training-journal.css?v=60d5c747',
  './styles/training-v3/00-training-tokens.css?v=8c98e7f6',
  './styles/training-v3/categories/running.css?v=17a951ac',
  './styles/training-v3/categories/strength.css?v=9a3ad8a3',
  './styles/training-v3/categories/cycling.css?v=9254d836',
  './styles/training-v3/categories/climbing.css?v=d203fd01',
  './styles/training-v3/categories/sports.css?v=7d2a4709',
  './styles/training-v3/categories/rowing.css?v=e7b3fa0d',
  './styles/training-v3/categories/skiing.css?v=19de51bb',
  './styles/training-v3/categories/health-training.css?v=cae4b117',
  './styles/training-v3/categories/yoga.css?v=8615901b',
  './styles/training-v3/categories/swimming.css?v=fa091b71',
  './styles/training-v3/categories/walking-hiking.css?v=b2c7cc67',
  './styles/training-v3/categories/calisthenics.css?v=759c0b3c',
  './styles/training-v3/01-training-shell.css?v=f046529a',
  './styles/training-v3/02-training-cards.css?v=2265b6e4',
  './styles/training-v3/04-training-gateways.css?v=eb1120fd',
  './styles/training-v3/05-training-tabs.css?v=1bdb3510',
  './styles/training-v3/06-training-metrics.css?v=d645f92b',
  './styles/training-v3/07-training-rows.css?v=20c7fb0d',
  './styles/training-v3/08-training-actions.css?v=bab912bf',
  './styles/training-v3/09-training-week-calendar.css?v=bf78e9f8',
  './styles/training-v3/10-training-glass-icons-buttons.css?v=bf985670',
  './styles/training-v3/11-training-specialist-hero.css?v=d74957b5',
  './styles/training-v3/12-training-legacy-retirement.css?v=ebf0e957',
  './styles/training-v3/13-training-modals.css?v=05d37b48',
  './styles/training-v3/14-library-scroll-rows.css?v=1fd10a29',
  './styles/integrations.css?v=332e1527',
  './styles/achievement-card/00-ach-tokens.css?v=abdc4aa6',
  './styles/achievement-card/01-ach-card.css?v=2ce8911f',
  './styles/achievement-card/02-ach-surfaces.css?v=e9b9c015',
  './styles/achievement-card/03-ach-motion.css?v=d81da346',
  './v0.02.11-journeys.css?v=087ba817',
  './v0.02.45-illustrated-journey-map.css?v=7cbf31a8',
  './v0.02.43-journey-catalogue.css?v=46b8f5d7',
  './v0.02.12-home-modules.css?v=b92e77a8',
  './styles/home-v4/00-home-tokens.css?v=178ac57a',
  './v0.02.13-home-v2-visuals.css?v=832ed910',
  './v0.02.14-home-widget-shell.css?v=ef5f7273',
  './v0.02.15-home-widget-player-status.css?v=ec0913d7',
  './v0.02.16-home-parchment-modules.css?v=0464bb6e',
  './v0.02.18-home-feature-module.css?v=c28c196b',
  './v0.02.19-home-standard-module.css?v=118fd549',
  './v0.02.20-home-parchment-material.css?v=e4ab74d0',
  './v0.02.21-home-parchment-tokens.css?v=9a410963',
  './v0.02.22-home-component-primitives.css?v=0c65851a',
  './v0.02.24-home-classic-hud-character-stats.css?v=6852a68b',
  './v0.02.25-home-classic-hud-phase-3-6.css?v=02039f70',
  './v0.02.26-home-player-hud-rebuild.css?v=1f9c0ad9',
  './styles/quests-v4/00-quest-tokens.css?v=e1b8b13b',
  './styles/quests-v4/01-quest-glass.css?v=67818d39',
  './styles/quests-v4/02-quest-layout.css?v=31f684f2',
  './styles/quests-v4/03-quest-header.css?v=2a54dd40',
  './styles/quests-v4/04-quest-gateways.css?v=f9be5970',
  './styles/quests-v4/05-quest-icons.css?v=ba3276d1',
  './styles/quests-v4/06-quest-buttons.css?v=224018f7',
  './styles/quests-v4/07-quest-cards.css?v=4e6e0a43',
  './styles/quests-v4/08-quest-rows.css?v=e56bf646',
  './styles/quests-v4/09-quest-tabs.css?v=b7de41f8',
  './styles/quests-v4/10-quest-progress.css?v=4719a410',
  './styles/quests-v4/11-quest-forms.css?v=f72966c5',
  './styles/quests-v4/12-quest-modals.css?v=48ecad8a',
  './styles/quests-v4/13-quest-popovers.css?v=2e20c1f3',
  './styles/quests-v4/14-quest-toasts.css?v=39369ee3',
  './styles/quests-v4/15-quest-responsive.css?v=f97f226d',
  './styles/quests-v4/16-quest-themes.css?v=3bcde247',
  './styles/quests-v4/17-quest-quick.css?v=255a354b',
  './styles/log-v1/00-log-shell.css?v=d3e85276',
  './styles/log-v1/01-log-calendar.css?v=4ca4143b',
  './styles/log-v1/02-log-modals.css?v=9f0b857d',
  './styles/log-v1/03-log-items.css?v=ca954acb',
  './styles/arrange/00-arrange.css?v=88f556e2',
  './styles/home-quick-quest.css?v=a055ddf6',
  './styles/personal-growth/00-pg-theme.css?v=3f6c7917',
  './styles/personal-growth/01-pg-components.css?v=36fbbae5',
  './styles/personal-growth/02-pg-pages.css?v=8862bac5',
  './styles/personal-growth/03-pg-detail.css?v=250b9ee9',
  './styles/weekly-recap/00-recap.css?v=bd2e8d69',
  './styles/onboarding/00-onboarding.css?v=427cd077',
  './styles/notifications/00-notifications.css?v=80245d89',
  './styles/library/00-lib-theme.css?v=8f911646',
  './styles/library/01-lib-components.css?v=77a8d702',
  './styles/library/02-lib-detail.css?v=30705c18',
  './styles/inventory-v1/00-inv-tokens.css?v=bb72db28',
  './styles/inventory-v1/01-inv-components.css?v=2a093d9a',
  './styles/economy/00-economy.css?v=e2b4c2b5',
  './styles/home-compact/00-compact-trackers.css?v=ebe996d4',
  './styles/self-care/00-self-care.css?v=983ef75a',
  './app.js?v=e668e3c1',
  './v0.02.17-exercise-library.js?v=99bd1b56',
  './v0.02.4-integration.js?v=bfee163b',
  './v0.02.49-sleep-hidden-progress.js?v=63ecb995',
  './v0.02.4.1-frame-hotfix.js?v=730d3831',
  './v0.02.4.2-character.js?v=6f11d2b6',
  './v0.02.4.3-player-box.js?v=9c1ac0aa',
  './v0.02.4.4-player-box-cleanup.js?v=d76ba53e',
  './v0.02.4.5-player-box-layout.js?v=6e8ec233',
  './v0.02.4.6-player-frame-controls.js?v=8ddf4843',
  './v0.02.4.11-player-box-progression-fix.js?v=302e37c4',
  './v0.02.4.7-weather-panel.js?v=b42ec168',
  './v0.02.4.8-today-panel.js?v=1e71a258',
  './v0.02.4.9-resources-panel.js?v=dc54233d',
  './v0.02.4.10-navigation.js?v=816da747',
  './v0.02.4.13-today-controls-extension.js?v=3f1e3e5c',
  './v0.02.4.16-resources-header-fix.js?v=5388a60c',
  './v0.02.15-home-widget-player-status.js?v=f3253fff',
  './v0.02.27-health-connect-bridge.js?v=429403e1',
  './v0.02.29-training-gear.js?v=2dbc689a',
  './v0.02.30-training-import.js?v=cbeca351',
  './v0.02.31-strava-adapter.js?v=efe86032',
  './v0.02.32-integrations-ui.js?v=c20c9f6d',
  './v0.02.33-quick-quests.js?v=b4441404',
  './v0.02.34-personal-growth.js?v=6081728a',
  './v0.02.35-library.js?v=5c848db9',
  './v0.02.46-economy-config.js?v=8eb0a1f0',
  './v0.02.36-inventory.js?v=3127d040',
  './v0.02.37-inventory-ui.js?v=d6db8db2',
  './v0.02.47-economy-core.js?v=80e00cbd',
  './v0.02.48-economy-ui.js?v=082a37a5',
  './v0.02.50-self-care.js?v=0a052d34',
  './v0.02.51-self-care-ui.js?v=19e3478b',
  './v0.02.52-pg-habits-hobbies-detail.js?v=e2f9a31d',
  './v0.02.53-pg-reading-nook.js?v=e2da68c6',
  './v0.02.54-pg-records-feed.js?v=231f14e6',
  './v0.02.55-weekly-recap.js?v=3b496ad7',
  './v0.02.56-onboarding.js?v=3945c391',
  './v0.02.57-notifications.js?v=1b87c87d',
  './v0.02.58-dev-tools.js?v=ce1050ac',
  './v0.02.59-compact-home-trackers.js?v=eee04932',
  './v0.02.60-scroll-bars.js?v=b5b6af98',
  './v0.02.39-world-tours-map.js?v=156ac755',
  './v0.02.44-illustrated-journey-map.js?v=dd9f43b6',
  './v0.02.40-hadrians-wall-illustrated-map.js?v=dc7e96ab',
  './v0.02.61-rome-illustrated-map.js?v=5ac5ae0a',
  './v0.02.63-camino-illustrated-map.js?v=cd9f6cc5',
  './v0.02.65-page-arrange.js?v=71e8fa78',
  './v0.02.65-page-arrange-specs.js?v=46a429b5',
  './v0.02.66-quest-completions.js?v=75889182',
  './v0.02.67-adventurers-log.js?v=27d26752',
  './v0.02.68-log-page.js?v=708097ad',
  './v0.02.64-route-66-illustrated-map.js?v=8b5f4351',
  './v0.02.62-update-banner.js?v=aad9469f',
  './v0.02.42-journey-catalogue.js?v=a382da8c',
  './manifest.json',
  './version.json',
  './assets/Class System/Icons/Starter Classes/novice_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/warrior_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scout_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scholar_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/artisan_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/steward_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/diplomat_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/adventurer_icon.png?v=0.1.2.5',
  './assets/Character/Stats/stat_str.png?v=0.1.2.5',
  './assets/Character/Stats/stat_dex.png?v=0.1.2.5',
  './assets/Character/Stats/stat_con.png?v=0.1.2.5',
  './assets/Character/Stats/stat_int.png?v=0.1.2.5',
  './assets/Character/Stats/stat_wis.png?v=0.1.2.5',
  './assets/Character/Stats/stat_cha.png?v=0.1.2.5',
  './assets/Training/Variant Other 2.png?v=0.1.2.5',
  './assets/Home/V3/Material/PARCHMENT_TEXTURE_512.png',
  './assets/Home/V3/Character/Stats/STAT_HP.png',
  './assets/Home/V3/Character/Stats/STAT_STAMINA.png',
  './assets/Home/V3/Character/Stats/STAT_DAMAGE.png',
  './assets/Home/V3/Character/Stats/STAT_DEFENCE.png',
  './assets/Home/V3/Character/Stats/STAT_FOCUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_STATUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_PORTRAIT.png',
  './assets/Home/Widget Family/BADGE_HOME_PLAYER_LEVEL.png',
  './assets/Home/Widget Family/BANNER_HOME_WIDGET_FEATURE.png',
  './assets/Home/Widget Family/PANEL_HOME_FEATURE_MEDIUM.png',
  './assets/Home/Widget Family/PANEL_HOME_STANDARD.png',
  './assets/Home/Widget Family/PANEL_HOME_COMPACT.png',
  './assets/Home/Widget Family/HEADER_HOME_WIDGET.png',
  './assets/Home/Widget Family/BUTTON_HOME_WIDGET.png',
  './assets/Home/Widget Family/INSET_HOME_STAT.png',
  './assets/Home/Widget Family/DIVIDER_HOME_WIDGET.png',
  './assets/backgrounds/home/BG_HOME_DAY.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_SUNSET.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_NIGHT.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_RAIN.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_TOP.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_BOTTOM.png?v=0.1.2.33',
  './assets/UI/shared/overlays/VIGNETTE_HOME.png?v=0.1.2.33',
  './assets/UI/shared/overlays/FX_HOME_RAIN.png?v=0.1.2.33',
  './assets/Home/Variant 8/Variant 8 - Player Panel Frame Only.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings Control Fix.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Player Panel Overlay.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Class Icon Frame.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Level Badge.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Help.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - HP.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Stamina.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Damage.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Defence.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Focus.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Streak.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Today.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Next Reward.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - XP Bar.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Divider.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Common_First_Sip.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Uncommon_Well_Watered.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Rare_Hydration_Habit.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Epic_River_Runner.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Legendary_The_Human_Reservoir.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Mythic_Ocean_in_Mortal_Form.webp?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Secret_Is_This_Mostly_Water_Now.webp?v=0.1.2.5',
  './assets/Achievements/achievement_placeholder_not_ready_yet.webp?v=0.1.2.21',
  './assets/Daily_Challenge.png',
  './assets/Development.png',
  './assets/Resources.png',
  './assets/Home_Logo.png',
  './assets/history_icon.png',
  './assets/habits_tracker_icon.png',
  './assets/bonus_icon.png',
  './assets/archive_icon.png',
  './assets/resources/home_resources_tracker_badge_variant_b_v1.png',
  './assets/resources/home_resources_history_badge_variant_b_v1.png',
  './assets/app-icon-192.png',
  './assets/app-icon-512.png',
  './assets/app-icon-maskable-192.png',
  './assets/app-icon-maskable-512.png',
  './assets/favicon-32.png',
  './assets/favicon-64.png',
  './assets/apple-touch-icon.png',
  './assets/UI/nav_menu_button.png?v=0.1.2.5',
  './assets/UI/nav_radial_background.png?v=0.1.2.5',
  './assets/UI/nav_storage.png?v=0.1.2.5',
  './assets/UI/nav_personal_growth.png?v=0.1.2.5',
  './assets/UI/nav_quest_board.png?v=0.1.2.5',
  './assets/UI/nav_training.png?v=0.1.2.5',
  './assets/UI/nav_achievements.png?v=0.1.2.5',
  './assets/UI/nav_loot.png?v=0.1.2.5',
  './assets/UI/nav_library.png?v=0.1.2.5',
  './assets/UI/nav_social.png?v=0.1.2.5',
  './assets/nav_quest_board.png',
  './assets/social.png',
  './assets/Character/ailment_cold.png',
  './assets/Character/ailment_custom.png',
  './assets/Character/ailment_dehydrated.png',
  './assets/Character/ailment_fatigued.png',
  './assets/Character/ailment_fever.png',
  './assets/Character/ailment_headache.png',
  './assets/Character/ailment_injury.png',
  './assets/Character/ailment_knee_pain.png',
  './assets/Character/ailment_sleep_deprived.png',
  './assets/Character/ailment_sore_legs.png',
  './assets/Character/ailment_stomach_bug.png',
  './assets/Character/menu_equipment.png',
  './assets/Character/menu_profile_setup.png',
  './assets/Character/menu_rewards.png',
  './assets/Character/menu_skills.png',
  './assets/Training/archery.png?v=0.1.2.5',
  './assets/Training/basketball.png?v=0.1.2.5',
  './assets/Training/boxing.png?v=0.1.2.5',
  './assets/Training/climbing.png?v=0.1.2.5',
  './assets/Training/connection_apple_health.png?v=0.1.2.5',
  './assets/Training/connection_coros.png?v=0.1.2.5',
  './assets/Training/connection_fit_import.png?v=0.1.2.5',
  './assets/Training/connection_garmin.png?v=0.1.2.5',
  './assets/Training/connection_google_fit.png?v=0.1.2.5',
  './assets/Training/connection_health_connect.png?v=0.1.2.5',
  './assets/Training/connection_polar.png?v=0.1.2.5',
  './assets/Training/connection_strava.png?v=0.1.2.5',
  './assets/Training/connection_trainingpeaks.png?v=0.1.2.5',
  './assets/Training/connection_zwift.png?v=0.1.2.5',
  './assets/Training/cycling.png?v=0.1.2.5',
  './assets/Training/dance.png?v=0.1.2.5',
  './assets/Training/equestrian.png?v=0.1.2.5',
  './assets/Training/football.png?v=0.1.2.5',
  './assets/Training/golf.png?v=0.1.2.5',
  './assets/Training/hiking.png?v=0.1.2.5',
  './assets/Training/interval_run.png?v=0.1.2.5',
  './assets/Training/kayaking.png?v=0.1.2.5',
  './assets/Training/long_run.png?v=0.1.2.5',
  './assets/Training/martial_arts.png?v=0.1.2.5',
  './assets/Training/mobility.png?v=0.1.2.5',
  './assets/Training/recovery.png?v=0.1.2.5',
  './assets/Training/rest.png?v=0.1.2.5',
  './assets/Training/rowing.png?v=0.1.2.5',
  './assets/Training/rugby.png?v=0.1.2.5',
  './assets/Training/running.png?v=0.1.2.5',
  './assets/Training/skiing.png?v=0.1.2.5',
  './assets/Training/strength.png?v=0.1.2.5',
  './assets/Training/swimming.png?v=0.1.2.5',
  './assets/Training/table_tennis.png?v=0.1.2.5',
  './assets/Training/tennis.png?v=0.1.2.5',
  './assets/Training/trail_hiking.png?v=0.1.2.5',
  './assets/Training/volleyball.png?v=0.1.2.5',
  './assets/Training/yoga.png?v=0.1.2.5',
  './assets/weather-clear-night.png',
  './assets/weather-sleet.png',
  './assets/shared/home_shared_panel_frame_foreground_v8.png?v=0.1.2.5',
  './assets/today/home_today_main_quest_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_physical_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_mental_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_social_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_random_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_identity_icon_v1.png?v=0.1.2.18',
  './assets/today/home_today_daily_puzzle_icon_v1.png?v=0.1.2.18',
  './assets/Adventure/lost_fortress_campaign_banner_v1.png?v=0.1.2.19',
  './assets/icons/navigation/NAV_QUEST_BOARD.png?v=0.01.8.7.5',
  './assets/icons/navigation/NAV_TRAINING.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_CHARACTER.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LIBRARY.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_QUESTS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_ADVENTURES.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LOG.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_GROWTH.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_SOCIAL.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_REWARDS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_HOME.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_INVENTORY.png?v=0.01.8.7.6',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_262.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_262_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_288.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_288_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_324.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_324_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_304.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_304_2x.png?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_352.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_352_2x.png?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FILL_412.svg?v=0.1.3.1',
  './assets/Home/V3/Navigation/OptionB3/OPTION_B3_FRAME_412_2x.png?v=0.1.3.1',
  './assets/Home/V3/Identity/HUD_REWARDS_40.png',
  './assets/Home/V3/Identity/HUD_REWARDS_80.png',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_BACKING_50.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_SPOKES.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_STYLIZED.png?v=0.1.2.1',
  './assets/icons/development/ICON_DEV_WORD.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_WISDOM.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_CHALLENGE.png?v=0.1.2.27',
];
/* Install caches the shell FILE BY FILE (RPG-0106). cache.addAll() is all-or-nothing: one missing file used to fail the whole install
   silently and leave the phone with no offline app. Now a miss is logged and skipped; only the two files the app cannot start
   without (index.html, app.js) can fail the install. Files that are not content-hashed (the page, manifest, version.json) are
   fetched past the browser's HTTP cache so a new worker never precaches yesterday's copy. */
self.addEventListener('install',event=>{
  event.waitUntil(caches.open(CACHE).then(async cache=>{
    const results=await Promise.allSettled(ASSETS.map(u=>cache.add(new Request(u,{cache:/\?v=/.test(u)?'default':'reload'}))));
    const missed=ASSETS.filter((u,i)=>results[i].status==='rejected');
    missed.forEach(u=>console.warn('[sw] not cached:',u));
    const critical=missed.filter(u=>u==='./'||/^\.\/(index\.html|app\.js)(\?|$)/.test(u));
    if(critical.length)throw new Error('[sw] cannot install without: '+critical.join(', '));
  }));
  self.skipWaiting();
});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('rpg-')&&k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
/* Fetch strategy (RPG-0109).
   - Content-hashed files (?v=<8 hex>, see scripts/sync-version.py) can never be stale, so they are served cache-first: opening the app
     no longer waits on the network for ~50 scripts and styles.
   - The page itself, version.json, the manifest and the worker are always revalidated with the server (cache:'no-cache': the ETag
     round trip is cheap), instead of trusting the 10 minutes GitHub Pages lets the browser keep them, so a fresh deploy shows up
     within a reload instead of after up to 10 minutes.
   - Everything else stays network-first with the cached copy as the offline fallback, exactly as before. */
const FRESH_PATHS=['/index.html','/version.json','/service-worker.js','/manifest.json'];
self.addEventListener('fetch',event=>{
  const req=event.request;
  if(req.method!=='GET')return;
  const url=new URL(req.url),same=url.origin===self.location.origin;
  const keep=response=>{
    if(response&&(response.ok||response.type==='opaque')){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(req,copy)).catch(()=>{})}
    return response;
  };
  if(same&&/[?&]v=[0-9a-f]{8}$/.test(url.search)){
    event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(keep)));
    return;
  }
  const fresh=same&&(req.mode==='navigate'||url.pathname.endsWith('/')||FRESH_PATHS.some(p=>url.pathname.endsWith(p)));
  event.respondWith((fresh?fetch(url.href,{cache:'no-cache'}):fetch(req)).then(keep).catch(()=>caches.match(req).then(hit=>{
    if(hit)return hit;
    if(req.mode==='navigate')return caches.match('./index.html');
    return Response.error();
  })));
});

/* RPG-0071: tapping a reminder (a system notification shown by the notification engine) focuses the app, or opens it. */
self.addEventListener('notificationclick', event => {
  event.notification.close();
  event.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) { if ('focus' in c) return c.focus(); }
    return self.clients.openWindow('./');
  }));
});
