// v0.1.2.5 BASELINE — Home Player Box, Weather, Today, Resources, and
// Navigation redesign, plus the Development -> Personal Growth move.
// v0.1.2.11 — Today restructured per home-definitive-spec.md, Resources
// header centered, v0.02.1.3 crest icon pack wired in.
const CACHE='rpg-v0.1.2.122';
const ASSETS=[
  './assets/Class System/Icons/Starter Classes/novice_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/warrior_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scout_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/scholar_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/artisan_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/steward_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/diplomat_icon.png?v=0.1.2.5',
  './assets/Class System/Icons/Starter Classes/adventurer_icon.png?v=0.1.2.5',
  './assets/Character/Stats/stat_str.png?v=0.1.2.5',
  './assets/Character/Stats/stat_dex.png?v=0.1.2.5',
  './assets/Character/Stats/stat_con.png?v=0.1.2.5',
  './assets/Character/Stats/stat_int.png?v=0.1.2.5',
  './assets/Character/Stats/stat_wis.png?v=0.1.2.5',
  './assets/Character/Stats/stat_cha.png?v=0.1.2.5',
  './assets/Training/Variant Other 2.png?v=0.1.2.5',
  './',
  './index.html',
  './styles.css?v=0.1.2.13',
  './app.js?v=0.1.2.121',
  './v0.02.17-exercise-library.js?v=0.1.2.2',
  './v0.02.4-integration.js?v=0.1.2.66',
  './v0.02.9-quests-hub.css?v=0.1.2.28',
  './v0.02.10-training-journal.css?v=0.1.2.34',
  './v0.02.11-journeys.css?v=0.1.2.31',
  './v0.02.12-home-modules.css?v=0.1.2.32',
  './v0.02.13-home-v2-visuals.css?v=0.1.2.38',
  './v0.02.14-home-widget-shell.css?v=0.1.2.36',
  './v0.02.15-home-widget-player-status.css?v=0.1.2.111',
  './v0.02.16-home-parchment-modules.css?v=0.1.2.89',
  './v0.02.18-home-feature-module.css?v=0.1.2.3',
  './v0.02.19-home-standard-module.css?v=0.1.2.4',
  './v0.02.20-home-parchment-material.css?v=0.1.2.2',
  './v0.02.21-home-parchment-tokens.css?v=0.1.2.1',
  './v0.02.22-home-component-primitives.css?v=0.1.2.1',
  './v0.02.23-quests-page-main-quest-surface.css?v=0.1.2.1',
  './assets/Home/V3/Material/PARCHMENT_TEXTURE_512.png',
  './v0.02.15-home-widget-player-status.js?v=0.1.2.98',
  './assets/Home/V3/Character/Stats/STAT_HP.png',
  './assets/Home/V3/Character/Stats/STAT_STAMINA.png',
  './assets/Home/V3/Character/Stats/STAT_DAMAGE.png',
  './assets/Home/V3/Character/Stats/STAT_DEFENCE.png',
  './assets/Home/V3/Character/Stats/STAT_FOCUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_STATUS.png',
  './assets/Home/Widget Family/FRAME_HOME_PLAYER_PORTRAIT.png',
  './assets/Home/Widget Family/BADGE_HOME_PLAYER_LEVEL.png',
  './assets/Home/Widget Family/BANNER_HOME_WIDGET_FEATURE.png',
  './assets/Home/Widget Family/PANEL_HOME_FEATURE_MEDIUM.png',
  './assets/Home/Widget Family/PANEL_HOME_STANDARD.png',
  './assets/Home/Widget Family/PANEL_HOME_COMPACT.png',
  './assets/Home/Widget Family/HEADER_HOME_WIDGET.png',
  './assets/Home/Widget Family/BUTTON_HOME_WIDGET.png',
  './assets/Home/Widget Family/INSET_HOME_STAT.png',
  './assets/Home/Widget Family/DIVIDER_HOME_WIDGET.png',
  './assets/backgrounds/home/BG_HOME_DAY.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_SUNSET.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_NIGHT.png?v=0.1.2.33',
  './assets/backgrounds/home/BG_HOME_RAIN.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_TOP.png?v=0.1.2.33',
  './assets/UI/shared/overlays/OVERLAY_HOME_BOTTOM.png?v=0.1.2.33',
  './assets/UI/shared/overlays/VIGNETTE_HOME.png?v=0.1.2.33',
  './assets/UI/shared/overlays/FX_HOME_RAIN.png?v=0.1.2.33',
  './v0.02.4.1-frame-hotfix.js?v=0.1.2.5',
  './v0.02.4.2-character.js?v=0.1.2.7',
  './v0.02.4.3-player-box.css?v=0.1.2.5',
  './v0.02.4.3-player-box.js?v=0.1.2.56',
  './v0.02.4.4-player-box-cleanup.css?v=0.1.2.5',
  './v0.02.4.4-player-box-cleanup.js?v=0.1.2.5',
  './v0.02.4.5-player-box-layout.css?v=0.1.2.5',
  './v0.02.4.5-player-box-layout.js?v=0.1.2.5',
  './v0.02.4.6-player-frame-controls.css?v=0.1.2.5',
  './v0.02.4.6-player-frame-controls.js?v=0.1.2.5',
  './v0.02.4.7-weather-panel.css?v=0.1.2.5',
  './v0.02.4.7-weather-panel.js?v=0.1.2.5',
  './v0.02.4.8-today-panel.css?v=0.1.2.5',
  './v0.02.4.8-today-panel.js?v=0.1.2.9',
  './v0.02.4.9-resources-panel.css?v=0.1.2.5',
  './v0.02.4.9-resources-panel.js?v=0.1.2.5',
  './v0.02.4.10-navigation.css?v=0.1.2.30',
  './v0.02.4.10-navigation.js?v=0.1.2.6',
  './assets/Home/Variant 8/Variant 8 - Player Panel Frame Only.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings Control Fix.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Player Panel Overlay.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Class Icon Frame.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Level Badge.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Help.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Settings.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - HP.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Stamina.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Damage.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Defence.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Focus.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Streak.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Today.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Next Reward.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - XP Bar.png?v=0.1.2.5',
  './assets/Home/Variant 8/Variant 8 - Divider.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Common_First_Sip.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Uncommon_Well_Watered.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Rare_Hydration_Habit.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Epic_River_Runner.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Legendary_The_Human_Reservoir.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Mythic_Ocean_in_Mortal_Form.png?v=0.1.2.5',
  './assets/Achievements/Hydration/Positive/Hydration_Achievement_Secret_Is_This_Mostly_Water_Now.png?v=0.1.2.5',
  './assets/Achievements/achievement_placeholder_not_ready_yet.png?v=0.1.2.21',
  './assets/Achievements/Frames/Achievement_Frame_Secret_Hidden.png?v=0.1.2.5',
  './manifest.json',
  './version.json',
  './assets/Daily_Challenge.png',
  './assets/Development.png',
  './assets/Resources.png',
  './assets/Home_Logo.png',
  './assets/history_icon.png',
  './assets/habits_tracker_icon.png',
  './assets/bonus_icon.png',
  './assets/archive_icon.png',
  './assets/resources/home_resources_tracker_badge_variant_b_v1.png',
  './assets/resources/home_resources_history_badge_variant_b_v1.png',
  './assets/app-icon-192.png',
  './assets/app-icon-512.png',
  './assets/app-icon-maskable-192.png',
  './assets/app-icon-maskable-512.png',
  './assets/apple-touch-icon.png',
  './assets/UI/nav_menu_button.png?v=0.1.2.5',
  './assets/UI/nav_radial_background.png?v=0.1.2.5',
  './assets/UI/nav_storage.png?v=0.1.2.5',
  './assets/UI/nav_personal_growth.png?v=0.1.2.5',
  './assets/UI/nav_quest_board.png?v=0.1.2.5',
  './assets/UI/nav_training.png?v=0.1.2.5',
  './assets/UI/nav_achievements.png?v=0.1.2.5',
  './assets/UI/nav_loot.png?v=0.1.2.5',
  './assets/UI/nav_library.png?v=0.1.2.5',
  './assets/UI/nav_social.png?v=0.1.2.5',
  './assets/nav_quest_board.png',
  './assets/social.png',
  './assets/Character/ailment_cold.png',
  './assets/Character/ailment_custom.png',
  './assets/Character/ailment_dehydrated.png',
  './assets/Character/ailment_fatigued.png',
  './assets/Character/ailment_fever.png',
  './assets/Character/ailment_headache.png',
  './assets/Character/ailment_injury.png',
  './assets/Character/ailment_knee_pain.png',
  './assets/Character/ailment_sleep_deprived.png',
  './assets/Character/ailment_sore_legs.png',
  './assets/Character/ailment_stomach_bug.png',
  './assets/Character/menu_equipment.png',
  './assets/Character/menu_profile_setup.png',
  './assets/Character/menu_rewards.png',
  './assets/Character/menu_skills.png',
  './assets/Training/archery.png?v=0.1.2.5',
  './assets/Training/basketball.png?v=0.1.2.5',
  './assets/Training/boxing.png?v=0.1.2.5',
  './assets/Training/climbing.png?v=0.1.2.5',
  './assets/Training/connection_apple_health.png?v=0.1.2.5',
  './assets/Training/connection_coros.png?v=0.1.2.5',
  './assets/Training/connection_fit_import.png?v=0.1.2.5',
  './assets/Training/connection_garmin.png?v=0.1.2.5',
  './assets/Training/connection_google_fit.png?v=0.1.2.5',
  './assets/Training/connection_health_connect.png?v=0.1.2.5',
  './assets/Training/connection_polar.png?v=0.1.2.5',
  './assets/Training/connection_strava.png?v=0.1.2.5',
  './assets/Training/connection_trainingpeaks.png?v=0.1.2.5',
  './assets/Training/connection_zwift.png?v=0.1.2.5',
  './assets/Training/cycling.png?v=0.1.2.5',
  './assets/Training/dance.png?v=0.1.2.5',
  './assets/Training/equestrian.png?v=0.1.2.5',
  './assets/Training/football.png?v=0.1.2.5',
  './assets/Training/golf.png?v=0.1.2.5',
  './assets/Training/hiking.png?v=0.1.2.5',
  './assets/Training/interval_run.png?v=0.1.2.5',
  './assets/Training/kayaking.png?v=0.1.2.5',
  './assets/Training/long_run.png?v=0.1.2.5',
  './assets/Training/martial_arts.png?v=0.1.2.5',
  './assets/Training/mobility.png?v=0.1.2.5',
  './assets/Training/recovery.png?v=0.1.2.5',
  './assets/Training/rest.png?v=0.1.2.5',
  './assets/Training/rowing.png?v=0.1.2.5',
  './assets/Training/rugby.png?v=0.1.2.5',
  './assets/Training/running.png?v=0.1.2.5',
  './assets/Training/skiing.png?v=0.1.2.5',
  './assets/Training/strength.png?v=0.1.2.5',
  './assets/Training/swimming.png?v=0.1.2.5',
  './assets/Training/table_tennis.png?v=0.1.2.5',
  './assets/Training/tennis.png?v=0.1.2.5',
  './assets/Training/trail_hiking.png?v=0.1.2.5',
  './assets/Training/volleyball.png?v=0.1.2.5',
  './assets/Training/yoga.png?v=0.1.2.5',
  './assets/weather-clear-night.png',
  './assets/weather-sleet.png',
  './assets/shared/home_shared_panel_frame_foreground_v8.png?v=0.1.2.5',
  './assets/today/home_today_main_quest_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_physical_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_mental_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_social_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_random_icon_v1.png?v=0.1.2.5',
  './assets/today/home_today_daily_challenge_identity_icon_v1.png?v=0.1.2.18',
  './assets/today/home_today_daily_puzzle_icon_v1.png?v=0.1.2.18',
  './assets/Adventure/lost_fortress_campaign_banner_v1.png?v=0.1.2.19',
  './assets/icons/navigation/NAV_QUEST_BOARD.png?v=0.01.8.7.5',
  './assets/icons/navigation/NAV_TRAINING.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_CHARACTER.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LIBRARY.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_QUESTS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_ADVENTURES.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_LOG.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_GROWTH.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_SOCIAL.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_REWARDS.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_HOME.png?v=0.01.8.7.6',
  './assets/icons/navigation/NAV_INVENTORY.png?v=0.01.8.7.6',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_FILL_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_262.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_288.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/NAV_DOCK_OUTLINE_324.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_262.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_262_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_288.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_288_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FILL_324.svg?v=0.1.2.2',
  './assets/Home/V3/Navigation/OptionB/OPTION_B_FRAME_324_2x.png?v=0.1.2.2',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_BACKING_50.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_SPOKES.svg?v=0.1.2.1',
  './assets/Home/V3/Navigation/Stylized/NAV_WHEEL_STYLIZED.png?v=0.1.2.1',
  './assets/icons/development/ICON_DEV_WORD.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_WISDOM.png?v=0.1.2.27',
  './assets/icons/development/ICON_DEV_CHALLENGE.png?v=0.1.2.27',
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  event.respondWith(fetch(event.request).then(response=>{
    const copy=response.clone();
    caches.open(CACHE).then(cache=>cache.put(event.request,copy)).catch(()=>{});
    return response;
  }).catch(()=>caches.match(event.request).then(hit=>{
    if(hit)return hit;
    if(event.request.mode==='navigate')return caches.match('./index.html');
    return Response.error();
  })));
});
